import { MenuItem, MenuCategory } from "@/types";

export const mockCategories: MenuCategory[] = [
  {
    id: "cat-1",
    name: "Appetizer",
    slug: "appetizer",
    icon: "utensils",
    display_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    name: "Soup",
    slug: "soup",
    icon: "soup",
    display_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    name: "Beverages",
    slug: "beverages",
    icon: "coffee",
    display_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    name: "Salad",
    slug: "salad",
    icon: "salad",
    display_order: 4,
    created_at: new Date().toISOString(),
  },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: "item-1",
    name: "Onigiri",
    description: "Japanese rice balls with various fillings",
    price: 12.9,
    image_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400",
    category_id: "cat-1",
    is_available: true,
    is_featured: true,
    preparation_time: 10,
    variations: [
      {
        id: "var-1",
        name: "Size",
        required: true,
        options: [
          { id: "opt-1", name: "Small", price_modifier: 0 },
          { id: "opt-2", name: "Medium", price_modifier: 3.0 },
          { id: "opt-3", name: "Large", price_modifier: 6.0 },
        ],
      },
    ],
    add_ons: [
      { id: "addon-1", name: "Extra Filling", price: 2.5, description: "Double the filling" },
      { id: "addon-2", name: "Seaweed Wrap", price: 1.0 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-2",
    name: "Songpyeon",
    description: "Traditional Korean rice cakes",
    price: 4.9,
    image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400",
    category_id: "cat-1",
    is_available: true,
    is_featured: true,
    preparation_time: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-3",
    name: "Miso Soup",
    description: "Traditional Japanese soup with tofu and seaweed",
    price: 5.5,
    image_url: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400",
    category_id: "cat-2",
    is_available: true,
    is_featured: false,
    preparation_time: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-4",
    name: "Green Tea",
    description: "Premium Japanese green tea",
    price: 3.5,
    image_url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    category_id: "cat-3",
    is_available: true,
    is_featured: false,
    preparation_time: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-5",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with caesar dressing",
    price: 8.5,
    image_url: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
    category_id: "cat-4",
    is_available: true,
    is_featured: false,
    preparation_time: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-6",
    name: "Spring Rolls",
    description: "Crispy vegetable spring rolls with dipping sauce",
    price: 6.9,
    image_url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400",
    category_id: "cat-1",
    is_available: true,
    is_featured: false,
    preparation_time: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-7",
    name: "Tom Yum Soup",
    description: "Spicy Thai soup with shrimp and mushrooms",
    price: 9.5,
    image_url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400",
    category_id: "cat-2",
    is_available: true,
    is_featured: true,
    preparation_time: 15,
    variations: [
      {
        id: "var-2",
        name: "Spice Level",
        required: true,
        options: [
          { id: "opt-4", name: "Mild", price_modifier: 0 },
          { id: "opt-5", name: "Medium", price_modifier: 0 },
          { id: "opt-6", name: "Hot", price_modifier: 0 },
          { id: "opt-7", name: "Extra Hot", price_modifier: 1.0 },
        ],
      },
      {
        id: "var-3",
        name: "Size",
        required: false,
        options: [
          { id: "opt-8", name: "Regular", price_modifier: 0 },
          { id: "opt-9", name: "Large", price_modifier: 3.0 },
        ],
      },
    ],
    add_ons: [
      { id: "addon-3", name: "Extra Shrimp", price: 4.0 },
      { id: "addon-4", name: "Extra Mushrooms", price: 2.0 },
      { id: "addon-5", name: "Coconut Milk", price: 1.5 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-8",
    name: "Iced Coffee",
    description: "Cold brewed coffee with ice",
    price: 4.0,
    image_url: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
    category_id: "cat-3",
    is_available: true,
    is_featured: false,
    preparation_time: 3,
    variations: [
      {
        id: "var-4",
        name: "Size",
        required: true,
        options: [
          { id: "opt-10", name: "Small", price_modifier: 0 },
          { id: "opt-11", name: "Medium", price_modifier: 1.0 },
          { id: "opt-12", name: "Large", price_modifier: 2.0 },
        ],
      },
    ],
    add_ons: [
      { id: "addon-6", name: "Extra Shot", price: 1.5 },
      { id: "addon-7", name: "Whipped Cream", price: 0.5 },
      { id: "addon-8", name: "Caramel Syrup", price: 0.5 },
      { id: "addon-9", name: "Vanilla Syrup", price: 0.5 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-9",
    name: "Greek Salad",
    description: "Fresh vegetables with feta cheese and olives",
    price: 7.5,
    image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400",
    category_id: "cat-4",
    is_available: false,
    is_featured: false,
    preparation_time: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "item-10",
    name: "Dumplings",
    description: "Steamed pork dumplings",
    price: 11.5,
    image_url: "https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=400",
    category_id: "cat-1",
    is_available: true,
    is_featured: false,
    preparation_time: 18,
    variations: [
      {
        id: "var-5",
        name: "Quantity",
        required: true,
        options: [
          { id: "opt-13", name: "6 pieces", price_modifier: 0 },
          { id: "opt-14", name: "12 pieces", price_modifier: 11.5 },
          { id: "opt-15", name: "18 pieces", price_modifier: 23.0 },
        ],
      },
    ],
    add_ons: [
      { id: "addon-10", name: "Extra Dipping Sauce", price: 1.0 },
      { id: "addon-11", name: "Chili Oil", price: 0.5 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

